### ISSUE TITLE
how do ex_phone_number support updates of (google libphonenumber) PhoneNumberMetadata.xml?

### ISSUE THREAD

**Issue by lohayon** [socialpaymentsbv/ex_phone_number#22]

**Comment by szymon-jez** [comment]
You can try to:

1. Replace [this file from the ex_phone_number repository](https://github.com/socialpaymentsbv/ex_phone_number/blob/b0d27690288ecca948711c572f58a9c043a80a5b/resources/PhoneNumberMetadata.xml) with [this file from google libphonenumber](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml).
2. Test if it works.
3. Add create a pull request here with the changes form point 1. We are welcome to update this.

**Comment by lohayon** [comment]
I am talking about a "live" update (an easy way to update that file) from time to time

**Comment by szymon-jez** [comment]
If you really need a "live" update then it could do steps 1. (to a different file) and 2. (but using the downloaded file) plus some option that would use the downloaded file instead of the one existing in the repository when compiling. So custom compiled library could be then deployed.
Though I don't see use cases where such a live update of that file would be needed.

**Comment by szymon-jez** [comment]
You are welcome.

The question was answered. Closing.
